version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: HelloWorld.API/Dockerfile
    ports:
      - "5000:80" # Porta exposta para testes externos
    networks:
      evaluation-network:
        aliases:
          - api

  gateway:
    build:
      context: .
      dockerfile: HelloWorld.Gateway/Dockerfile
    ports:
      - "8000:8080" # Mapear a porta 8000 do host para a porta 8080 do contêiner
    depends_on:
      - api
    networks:
      evaluation-network:
        aliases:
          - ocelot-gateway

networks:
  evaluation-network:
    external: true
