version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: HelloWorld.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  gateway:
    build:
      context: .
      dockerfile: HelloWorld.Gateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
