version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: HelloWorld.API/Dockerfile
    ports:
      - "8000:8080" # Porta exposta para testes externos
    networks:
      evaluation-network:
        aliases:
          - api

  gateway:
    container_name: ocelot-gateway
    build:
      context: .
      dockerfile: HelloWorld.Gateway/Dockerfile
    ports:
      - "7777:7777" # Mapear a porta 8000 do host para a porta 8080 do conteiner
    depends_on:
      - api
    networks:
      evaluation-network:
        aliases:
          - ocelot-gateway
    tty: true

networks:
  evaluation-network:
    external: true
